SUPABASE_URL = "https://ofcealgkyznqwzdiaiys.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mY2VhbGdreXpucXd6ZGlhaXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzMzMzEsImV4cCI6MjA2NjAwOTMzMX0.Hvnd4EuA8UnISzECxRbyxumzZs8FBrXtDpzJyPrX7iY"
